// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieList.pk.Database.Context;

namespace MovieList.pk.Database.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20220427191011_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("MovieList.pk.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsUnicode(false)
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "this is a test movie for one",
                            Name = "Test Movie One"
                        },
                        new
                        {
                            Id = 2,
                            Description = "this is a test movie for two",
                            Name = "Test Movie Two"
                        },
                        new
                        {
                            Id = 3,
                            Description = "this is a test movie for tree",
                            Name = "Test Movie three"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
